### ISSUE TITLE
[3DS] Tweak the default preset + other bugs

### ISSUE THREAD

**Issue by UltraSyko** [libretro/vitaquake2#27]
Bugs:
It's very laggy, especially audio
Restarting does nothing. You have to close the content

Recommended default settings
Default Internal Resolution is set to 960x544 which is way too high for o3DS and N3DS. HUD elements are way too small to read.
Downgrading it to the lowest setting, 480x272 feels more appropriate to read and gives a performance boost
Turn Rumble off since this platform doesn't have that feature

**Comment by LibretroAdmin** [comment]
Should have been resolved some time ago,

> #elif defined(_3DS)
>      "400x240"

This is the default resolution for 3DS.
