### ISSUE TITLE
[Android] Crashes on Android

### ISSUE THREAD

**Issue by bluemonkeysuit07** [libretro/vitaquake2#29]
Tried this core on NVIDIA shield tv , Samsung galaxy S10, Samsung tab s2 and retroarch instantly closes on all these devices when trying to run the vitaquake2 core

**Comment by bluemonkeysuit07** [comment]
restored an older version of the core on galaxy s10 and it works fine

**Comment by s-cr0w** [comment]
Same issue for me, where did you get the older version of the core? Or did you compile yourself? :P

**Comment by bluemonkeysuit07** [comment]
it was on a backup i had

**Comment by bluemonkeysuit07** [comment]
would providing working and non working versions be of any help?

**Comment by inactive123** [comment]
These issues should be resolved now.

In case you are trying this with the shareware version downloaded from Content Downloader, download it again. It should work then.

**Comment by typhonthedestroyer** [comment]
Issue still not resolved please reopen
