### ISSUE TITLE
[Wii U] Loading content raises memory error

### ISSUE THREAD

**Issue by chrhaeusler** [libretro/vitaquake2#30]
Hello,

I have an issue when trying to start Quake II on a Wii U (Firmware 5.5.5E).   
Loading the core (v2.3; Retroarch 1.9.8) works but loading pak0.pak (md5sum 1ec55a724dc3109fd50dde71ab581d70) as content raises the following error:
```
DSI: Instr at 0D0FC064 bad write to unmapped memory at 0A076888
[...]
0D0EC7AC(000EC7AC): retroarch_launcher|R_EdgeDrawing.part.1
Retroarch 1.9.9 (39630391) built Aug 18 2021
```

Does anybody know what might cause that error?

Kind regards,
Chris

**Comment by Ploggy** [comment]
This doesn't happen for me with the latest version (1.9.13 - vitaQuakeII v2.3) using the Q2demo from the RA Content Downloader. 
So fixed :)
