### ISSUE TITLE
Previous game saves do not load anymore because of PR #45

### ISSUE THREAD

**Issue by DrUm78** [libretro/vitaquake2#46]
Device: FunKey S handheld (armv7 32-bit)
OS: FunKey OS (Linux 4.14.14)
Frontend: PicoArch
Build: latest 6bb3ee592169694b055e7efd5fa2a4e57875bddd

PR #45 breaks the loading of my old game saves, it just freezes the core in the save loading menu and nothing responds anymore. Newly created saves load fine though.

Here is the error I get thousands of times in my logs:
`INFO: LOG2FILE: Sys_Error: FS_Read: 0 bytes readINFO: LOG2FILE: Sys_Quit calledINFO: LOG2FILE: Sys_Error: recursive error after: FS_Read: 0 bytes readINFO: LOG2FILE: Sys_Quit calledrecursive shutdown`

I attached my saves (pick the one in the Detention Center): [save.zip](https://github.com/libretro/vitaquake2/files/12225860/save.zip)
![IMG_0212](https://github.com/libretro/vitaquake2/assets/46139740/2bb08d9a-44dd-4209-ba23-5f162f9f8aff)

**Comment by greenchili2** [comment]
The only impact I can think of that my change would have had on internal quake saves ( not savestates... there is a difference ) .. is that the quake engine is storing the gamesave path with the save and thus on attempting to read an old save it is reading in too many characters at that point and thus further reads of data fail.

I'll look at the code and see if that is the case.  But other than that.. it is the only change I made.

**Comment by greenchili2** [comment]
I was able to narrowed it down to function SV_ReadServerFile() in sv_ccmds.c being the culprit.  More info later.

**Comment by greenchili2** [comment]
Still looking at it.  I can easily fix it to read old saves.. however new saves would be broke and would have to be re-done.. :|

Due to how the code in question was written.  It was basically due to poor choice of variables used the best I can tell.

**Comment by DrUm78** [comment]
Indeed, I meant internal game saves, Quake II does not have any savestate anyway. Glad to see that you found the culprit function. 👍

**Comment by greenchili2** [comment]
This should do it.. I tested it on my old saves as well as a new one I created under PR #45.

https://github.com/libretro/vitaquake2/pull/47

Once the pull request is accepted you should be able to update it in the online core updater.

**Comment by DrUm78** [comment]
Works fine for me after a quick test with an old and a new game saves! 👍

**Comment by greenchili2** [comment]
> Works fine for me after a quick test with an old and a new game saves! 👍

Great!  You must have you're own compile environment for linux?

Interested in testing some updates to Hatari?

**Comment by DrUm78** [comment]
Yeah, I have my own fork of VitaQuake II which I modified for the FunKey S handheld: https://github.com/DrUm78/vitaquake2

I do not use Hatari core, should not be easy to use on a micro handheld with 240x240 screen without any keyboard. :D

**Comment by greenchili2** [comment]
> Yeah, I have my own fork of VitaQuake II which I modified for the FunKey S handheld: https://github.com/DrUm78/vitaquake2
> 
> I do not use Hatari core, should not be easy to use on a micro handheld without any keyboard. :D

Ahh I see.. Hatari has a virtual keyboard.. not the best but it has one.  But thanks anyways.  :D
